{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e316c9f4-50f9-4233-82f1-ef519a917dd5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "================================================================\n",
      "         SMARTCAMPUS UTILITY & ACCESS PASS GENERATOR\n",
      "================================================================\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter the category:(1: Student, 2: Faculty/Staff): 1\n",
      "enter sub category:(UG/PG): UG\n",
      "enter youe cgpa:(0.0 - 10.0): 8.8\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "100.0\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Select Parking Permit(0: None, 2: Two-Wheeler, 4: Four-Wheeler): 4\n",
      "enter the monthly consumption in kwh: 340\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "----------------------------------------------------------------\n",
      "                CALCULATED INVOICE BREAKDOWN\n",
      "----------------------------------------------------------------\n",
      "Base Access Pass Fee: Rs 500\n",
      "Merit Discount(20%):- Rs 100.0\n",
      "parking fee (4-wheeler):Rs 600\n",
      "Student Peak Surcharge : Rs 150\n",
      "Net Pass & Parking Total:Rs 1150.0\n",
      "----------------------------------------------------------------\n",
      "Electricity Bill(340KWh):Rs 1900.0(Slab calculated + Fixed Charge ₹150)\n",
      "----------------------------------------------------------------\n",
      "TOTAL MONTHLY PAYABLE:Rs 3050.0\n",
      "================================================================\n"
     ]
    }
   ],
   "source": [
    "print(\"================================================================\")\n",
    "print(\"         SMARTCAMPUS UTILITY & ACCESS PASS GENERATOR\")\n",
    "print(\"================================================================\")\n",
    "category=input(\"Enter the category:(1: Student, 2: Faculty/Staff):\")\n",
    "if category == \"Student\" or category == \"1\": \n",
    "  sub_category=input(\"enter sub category:(UG/PG):\")\n",
    "  if sub_category==\"UG\":\n",
    "      base_fee=500\n",
    "      \n",
    "  elif sub_category==\"PG\":\n",
    "      base_fee=350\n",
    "  else:\n",
    "      print(\"your input is invalid\")\n",
    "      raise SystemExit\n",
    "  if sub_category==\"UG\" or sub_category==\"PG\":\n",
    "      cgpa=float(input(\"enter youe cgpa:(0.0 - 10.0):\"))\n",
    "      if cgpa<0 or cgpa>10:\n",
    "          print(\"[ERROR]: CGPA must be between 0.0 and 10.0\")\n",
    "          raise SystemExit\n",
    "      discount=0\n",
    "      dis=0\n",
    "  \n",
    "      if cgpa>=8.5:\n",
    "          dis=20\n",
    "          discount=(base_fee*20)/100\n",
    "          print(discount)\n",
    "      elif 7.5<=cgpa<8.5:\n",
    "          dis=10\n",
    "          discount=(base_fee*10)/100\n",
    "     # else:\n",
    "      #    print(\"discount is noot applicable on your percentage\")\n",
    "          \n",
    "      if sub_category==\"UG\" or sub_category==\"PG\":   \n",
    "          parking=input(\"Select Parking Permit(0: None, 2: Two-Wheeler, 4: Four-Wheeler):\")\n",
    "          if  parking==\"0\" or parking==\"None\":\n",
    "              par=\"none\"\n",
    "              parking_fees=0\n",
    "          elif parking==\"2\" or parking==\"Two-wheeler\":\n",
    "               par=\"2-wheeler\" \n",
    "               parking_fees=200\n",
    "          elif parking==\"4\" or  parking==\" Four-Wheeler\":\n",
    "              par=\"4-wheeler\"\n",
    "              parking_fees=600\n",
    "          \n",
    "          else:\n",
    "              print(\"not in the list\")\n",
    "              raise SystemExit \n",
    "          surcharge=0\n",
    "          if parking==\"4\" or parking==\"Four-Wheeler\":\n",
    "              surcharge=150\n",
    "\n",
    "      if sub_category==\"UG\" or sub_category==\"PG\": \n",
    "          electricity=int(input(\"enter the monthly consumption in kwh:\"))\n",
    "          if electricity<0:\n",
    "              print(\"[ERROR]: Electricity units cannot be negative\")\n",
    "              raise SystemExit \n",
    "          if  electricity<=100:\n",
    "              elec=electricity*3+50\n",
    "          elif electricity<=300 and electricity>100:\n",
    "               elec=100*3+(electricity-100)*5+100+50\n",
    "          elif electricity<=500 and electricity>300:\n",
    "               elec=100*3+200*5+(electricity-300)*7.5+150+50+100 \n",
    "          elif electricity>500:\n",
    "               elec=100*3+200*5+200*7.5+(electricity-500)*10+250+50+100 \n",
    "elif  category == \"Faculty\" or category == \"2\" or category == \"Staff\": \n",
    "          sub_category=input(\"enter sub category:(Resident Faculty/(Guest/Visiting Faculty)):\")\n",
    "          if sub_category==\"Resident Faculty\":\n",
    "               base_fee=800\n",
    "      \n",
    "          elif sub_category==\"Guest Faculty\" or sub_category==\"Visiting Faculty\" :\n",
    "               base_fee=1200\n",
    "          else:\n",
    "               print(\"your input is invalid\")  \n",
    "               raise SystemExit \n",
    "          if sub_category==\"Guest Faculty\" or sub_category==\"Visiting Faculty\" or sub_category==\"Resident Faculty\":\n",
    "               service=float(input(\"enter your working years:(0.0 - 10.0):\"))\n",
    "               if service<0:\n",
    "                   print(\"[ERROR]: Years of Service cannot be negative\")\n",
    "                   raise SystemExit \n",
    "\n",
    "               discount=0\n",
    "               dis=0\n",
    "               if service>10:\n",
    "                 dis=15\n",
    "                 discount=( base_fee*15)/100\n",
    "               #else:\n",
    "                #   print(\"discount is not applicable\")\n",
    "               parking=input(\"Select Parking Permit(0: None, 2: Two-Wheeler, 4: Four-Wheeler):\")\n",
    "               if parking==\"0\" or parking==\"None\":\n",
    "                   par=\"none\"\n",
    "                   parking_fees=0\n",
    "               elif parking==\"2\" or parking==\"Two-wheeler\":\n",
    "                   par=\"2-wheeler\"\n",
    "                   parking_fees=200\n",
    "               elif parking==\"4\" or parking==\"Four-Wheeler\":\n",
    "                   par=\"4-wheeler\"\n",
    "                   parking_fees=600  \n",
    "               else:\n",
    "                   print(\"not in the list\")\n",
    "                   raise SystemExit \n",
    "               surcharge=0\n",
    "               electricity=int(input(\"enter the monthly consumption in kwh:\"))\n",
    "               if electricity<0:\n",
    "                     print(\"[ERROR]: Electricity units cannot be negative\")\n",
    "                     raise SystemExit\n",
    "               if  electricity<=100:\n",
    "                      elec=electricity*3+50\n",
    "               elif electricity<=300 and electricity>100:\n",
    "                      elec=100*3+(electricity-100)*5+100+50\n",
    "               elif electricity<=500 and electricity>300:\n",
    "                      elec=100*3+200*5+(electricity-300)*7.5+150+50+100   \n",
    "               elif electricity>500:\n",
    "                      elec=100*3+200*5+200*7.5+(electricity-500)*10+250+150  \n",
    "else:\n",
    "      print(\"[ERROR]: Invalid category\")\n",
    "      raise SystemExit              \n",
    "if category == \"Student\" or category == \"1\" or category == \"Faculty\" or category == \"2\" or category == \"Staff\"  :\n",
    "        print(\"----------------------------------------------------------------\")\n",
    "        print(\"                CALCULATED INVOICE BREAKDOWN\")\n",
    "        print(\"----------------------------------------------------------------\")\n",
    "        print(f\"Base Access Pass Fee: Rs {base_fee}\")\n",
    "        if category == \"Student\" or category == \"1\":\n",
    "           if cgpa>8.5:\n",
    "               print(f\"Merit Discount({dis}%):- Rs {discount}\")\n",
    "           elif 7.5<cgpa<8.5:    \n",
    "               print(f\"Merit Discount({dis}%):- Rs {discount}\") \n",
    "           else:\n",
    "                print(\"Merit Discount : Rs 0.00\")\n",
    "        elif category == \"Faculty\" or category == \"2\" or category == \"Staff\":\n",
    "           if service>10:\n",
    "                 print(f\"Service Discount({dis}%):- Rs {discount}\") \n",
    "           else:\n",
    "                print(\"Service Discount : Rs 0.00\")\n",
    "        if parking==\"2\" or parking==\"Two-wheeler\":\n",
    "                 print(f\"parking fee ({par}):Rs {parking_fees}\")\n",
    "    \n",
    "        elif  parking==\"0\" or parking==\"None\":\n",
    "                 print(f\"parking fee ({par}):Rs {parking_fees}\")  \n",
    "      \n",
    "        elif  parking==\"4\" or parking==\"four-wheeler\":\n",
    "                 print(f\"parking fee ({par}):Rs {parking_fees}\")\n",
    "                 if category==\"Student\" or category==\"1\":\n",
    "                         print(f\"Student Peak Surcharge : Rs {surcharge}\")\n",
    "        if category==\"Student\" or category==\"1\":\n",
    "            total=base_fee-discount+parking_fees+surcharge\n",
    "        else :\n",
    "                 total=base_fee-discount+parking_fees\n",
    "        print(f\"Net Pass & Parking Total:Rs {total}\")    \n",
    "        print(\"----------------------------------------------------------------\")\n",
    "        print(f\"Electricity Bill({electricity}KWh):Rs {elec}(Slab calculated + Fixed Charge ₹150)\")\n",
    "        print(\"----------------------------------------------------------------\")\n",
    "        print(f\"TOTAL MONTHLY PAYABLE:Rs {elec+total}\")\n",
    "        print(\"================================================================\")  \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "09258c93-1634-4d1f-ae79-088ab444d07d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3cc67dd5-54dc-4fd2-86dc-44b2b4824355",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
